# permissions for end users to edit s3envfiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: s3-configmap-controller
    app.kubernetes.io/managed-by: kustomize
  name: s3envfile-editor-role
rules:
- apiGroups:
  - config.greatlion.tech
  resources:
  - s3envfiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.greatlion.tech
  resources:
  - s3envfiles/status
  verbs:
  - get
