name: oci helm chart
on:
  release:
    types:
      - published
jobs:
  helmoci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Change app version
        run: |
          yq -i '.appVersion = "${{github.event.release.tag_name}}"' dist/chart/Chart.yaml
          yq -i 'controllerManager.container.image.tag = "${{github.event.release.tag_name}}"' dist/chart/values.yaml

      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: pbr-chart
          repository: greatliontech
          tag: ${{github.event.release.tag_name}}
          path: dist/chart
          registry: ghcr.io
          registry_username: thegrumpylion
          registry_password: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
