name: build & push image
on:
  release:
    types:
      - published
jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: thegrumpylion
          password: ${{ secrets.GORELEASER_GITHUB_TOKEN }}

      - name: Build and push
        run: |
          make docker-build docker-push IMG="ghcr.io/greatliontech/s3-configmap-controller:${{github.event.release.tag_name}}"
